# 第三章 流程控制

In [1]:
celsius=float(input('請輸入攝氏溫度:')) # 將輸入的攝氏溫度改為華氏溫度
fahrenheit=(9/5) * celsius + 32
print('華氏溫度為:',fahrenheit)

請輸入攝氏溫度:20
華氏溫度為: 68.0


In [2]:
import statistics as st # 匯入統計
sample=[5,8,9,6,4,1,2,3,5,6]
print('樣本=', sample)
print('平均數', st.mean(sample))
print('最大數', max(sample))
print('最小數', min(sample))
print('變異數', round(st.variance(sample),2))
print('標準差', round(st.stdev(sample), 2))

樣本= [5, 8, 9, 6, 4, 1, 2, 3, 5, 6]
平均數 4.9
最大數 9
最小數 1
變異數 6.32
標準差 2.51


# if

In [5]:
numA = int(input('請輸入numA:'))
numB = int(input('請輸入numB:'))
if numA < numB:
    print('numB是比較大的數')
elif numA > numB:
    print('numA是比較大的數')
else:
    print('numA和numB是相同的')

請輸入numA:3
請輸入numB:3
numA和numB是相同的


# for 迴圈

In [3]:
sum = 0
for i in range(1, 11): # 跑for迴圈，加總一到十之間的數
    sum = sum + i
print('總和:', sum)

總和: 55


In [9]:
sample=[5,8,9,6,4,1,2,3,5,6]
sum=0
for i in sample:
    sum=sum + i
print('總和:', sum)

總和: 49


# In-class exercise 隨堂練習
## 雞兔同籠問題進行求解 若共有35個頭 94隻腳 問共有幾隻雞?幾隻兔

In [13]:
head = 35
leg = 94
for rabbit in range(0, head+1):
    chicken = head - rabbit
    if((rabbit * 4 + chicken * 2) == 94):
        print('兔子有', rabbit, '隻')
        print('雞有', chicken, '隻')

兔子有 12 隻
雞有 23 隻


In [14]:
mylist='I Love Avengers IV'
for character in mylist:
    print(character)

I
 
L
o
v
e
 
A
v
e
n
g
e
r
s
 
I
V


# While 迴圈

# 1+2+3+...+10的總和

In [1]:
sum = 0
count = 1
while count <= 10:
    sum = sum + count # sum += count
    count = count + 1 # count += 1
print('1+2+3+...+10 = ', sum)

1+2+3+...+10 =  55


# 銀行利息範例

In [2]:
x = 10000
year = 0
while x < 20000: # 當存款還沒超過20000元的時候，就繼續
    year += 1
    x = x * 1.0104 # 1.0104 就是當前的利率
print(str(year), '年後，存款金額會加倍')

67 年後，存款金額會加倍


# 帳號密碼程式

In [4]:
id = 'hawk'
password = '84265'
while True:
    x = input('請輸入帳號 : ')
    y = input('請輸入密碼 : ')
    if(x == id and y == password):
        print('歡迎登入')
        break # 如果兩者都對，就跳脫while迴圈
    else:
        print('帳號或密碼輸入錯誤') # 如果其中之一不對，那就繼續跑迴圈

請輸入帳號 : 123
請輸入密碼 : 123
帳號或密碼輸入錯誤
請輸入帳號 : hawk
請輸入密碼 : 5656
帳號或密碼輸入錯誤
請輸入帳號 : uiui
請輸入密碼 : 84265
帳號或密碼輸入錯誤
請輸入帳號 : hawk
請輸入密碼 : 84265
歡迎登入


# break, continue, pass 範例

In [5]:
mylist = ['C#', 'Python', 'F#', 'JavaScript']
for script in mylist:
    if(script == 'F#'):
        break # 如果遇到F#就跳脫foreach
    else:
        print(script)   

C#
Python


In [6]:
mylist = ['C#', 'Python', 'F#', 'JavaScript']
for script in mylist:
    if(script == 'F#'):
        continue # 如果遇到F#那就繼續跑迴圈
    else:
        print(script)   

C#
Python
JavaScript


In [7]:
mylist = ['C#', 'Python', 'F#', 'JavaScript']
for script in mylist:
    if(script == 'F#'):
        pass # 如果遇到F#那就通過
    else:
        print(script) 

C#
Python
JavaScript


# 亂數

In [8]:
import random
for i in range(0, 10):
    print(random.random())

0.049971496965325435
0.46524349202051474
0.4139833687715604
0.0981418634438187
0.07845037828831158
0.4883252957268506
0.1967566793023625
0.1691434591375217
0.12970935530665395
0.77285731349732


In [9]:
for i in range(0, 10):
    print(random.randint(1, 9))

8
6
3
6
6
6
7
3
7
6


In [10]:
import random
number = random.randint(1,9)
while True:
    guess = input('請猜一個1-9的數字(q是離開):')
    if guess == 'q':
        print('離開遊戲,正確數字是-->', number)
        break
    else:
        if number == int(guess):
            print('恭喜，猜對了')
            break
        else:
            print('猜錯了')   

請猜一個1-9的數字(q是離開):1
猜錯了
請猜一個1-9的數字(q是離開):2
猜錯了
請猜一個1-9的數字(q是離開):3
猜錯了
請猜一個1-9的數字(q是離開):4
猜錯了
請猜一個1-9的數字(q是離開):5
猜錯了
請猜一個1-9的數字(q是離開):6
猜錯了
請猜一個1-9的數字(q是離開):7
猜錯了
請猜一個1-9的數字(q是離開):8
猜錯了
請猜一個1-9的數字(q是離開):9
恭喜，猜對了


# numpy套件

In [3]:
# numpy套件ndarray型態，提供element-wise的操作
import numpy as np
a_ndarray = np.array([6,7,8,9,10])
print(a_ndarray*9)

[54 63 72 81 90]


In [4]:
print(type(a_ndarray))
print(a_ndarray.ndim) # ndarray的維度
print(a_ndarray.shape) # ndarray的shape
print(a_ndarray.dtype) # ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [6]:
s=np.zeros(7)
print(s) # 7個元素都為0的一維陣列
print(np.zeros((2,7))) # 14個元素都為0的二維陣列
print(np.empty((3,7,3))) # 63個元素都為初始化的值
print(np.arange(12)) # 12個元素為0-11的一維陣列

[0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[[1.06313836e-311 1.06313851e-311 2.31222722e-321]
  [            nan 1.85843969e-229 2.10053203e-301]
  [2.49329550e-306 1.63422598e-301 1.08384688e-296]
  [4.59723154e-287 9.37698370e-273 2.58046969e-263]
  [1.94165660e-292 2.21763328e-301 3.82282279e-297]
  [3.12429791e-282 5.03166037e+204 1.07131023e-296]
  [4.71280699e-287 9.50334730e-273 1.45424407e-296]]

 [[1.94165662e-292 1.64612952e-287 2.21653674e-301]
  [4.54305905e-268 1.55787426e-307 1.07249955e-296]
  [1.34081024e-272 8.78476792e-268 1.41264609e-277]
  [7.07007366e-278 2.21653674e-301 4.09244559e-268]
  [7.02191385e-292 1.41264514e-277 9.28672379e-273]
  [1.45424407e-296 1.94165662e-292 1.55787426e-307]
  [3.74710271e-301 1.63400526e-301 1.63423312e-301]]

 [[1.63696068e-301 7.12553096e+175 5.17360531e-297]
  [8.85521664e-220 2.78222723e-308 1.63400526e-301]
  [3.73896578e-301 3.80922936e-210 2.49253257e-205]
  [8.48023363e-268 3.77406523e-258 3.477

# ndarray 進階操作

In [7]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [11]:
# 二維ndarray取值
my_2d_array = np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[0,:]) # 第一列資料
print(my_2d_array[:,0]) # 第一欄資料
print(my_2d_array[0,0]) # 第一列第一欄資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[0 5]
0


In [13]:
# 假設有六個組別"Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"
# 其參加人數分別為56, 8, 19, 14, 6, 71人
groups=["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironman = [56, 8, 19, 14, 6, 71]
groups_array = np.array(groups)
ironman_array = np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


In [14]:
# 用人數去篩選組別
print(ironman_array >= 10) # 組別有大於10人的印出來，但是是True or false
print(groups_array[ironman_array >= 10]) # 組別有大於10人的印出來
print(groups_array != "自我挑戰組") 
print(ironman_array[groups_array != "自我挑戰組"]) # 除了自我挑戰組以外的組別人數

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarray 轉置

In [15]:
my_1d_array = np.arange(10)
print(my_1d_array)
my_2d_array = my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [16]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [17]:
# ndarray nan(空值)
nan_array = np.array([50, 70, 60, 34, np.nan])
print(nan_array)

[50. 70. 60. 34. nan]


# Pandas Data Frame

In [1]:
import pandas as pd

groups=["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [56, 8, 19, 14, 6, 71]
ironmen_dict = {
    "groups": groups,
    "ironmen": ironmen       
               }
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df

groups  ironmen
0  Modern Web       56
1      DevOps        8
2       Cloud       19
3    Big Data       14
4    Security        6
5       自我挑戰組       71

In [3]:
print(ironmen_df.ndim) #印出維度
print(ironmen_df.shape) #印出幾乘幾
print(ironmen_df.dtypes) #印出型態  object 就是字串

2
(6, 2)
groups     object
ironmen     int64
dtype: object


In [4]:
print(ironmen_df.sum()) #印出總和 object 就是字串加起來
print(ironmen_df.ironmen.sum()) # 印出人數總和
print(ironmen_df.mean()) #印出平均數
print(ironmen_df.median()) #印出中位數
print(ironmen_df.describe()) #印出所有資料

groups     Modern WebDevOpsCloudBig DataSecurity自我挑戰組
ironmen                                           174
dtype: object
174
ironmen    29.0
dtype: float64
ironmen    16.5
dtype: float64
         ironmen
count   6.000000
mean   29.000000
std    27.524535
min     6.000000
25%     9.500000
50%    16.500000
75%    46.750000
max    71.000000


In [5]:
import pandas as pd
import numpy as np

groups=["Modern Web", "DevOps", np.nan, "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [56, 8, 19, 14, 6, 71, np.nan]
ironmen_dict = {
    "groups": groups,
    "ironmen": ironmen       
               }
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.loc[:, "groups"].isnull()) #判斷哪些組的組名事遺失值
print(ironmen_df.loc[:, "ironmen"].notnull()) #判斷哪些組的人數不是遺失值

0    False
1    False
2     True
3    False
4    False
5    False
6    False
Name: groups, dtype: bool
0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: ironmen, dtype: bool


In [6]:
a=ironmen_df.dropna() #刪除空值
b=ironmen_df.fillna(0) #空值補0
c=ironmen_df.fillna(ironmen_df.ironmen.mean()) #空值補平均數
a
b
c

groups  ironmen
0  Modern Web     56.0
1      DevOps      8.0
2          29     19.0
3       Cloud     14.0
4    Big Data      6.0
5    Security     71.0
6       自我挑戰組     29.0

In [8]:
import pandas as pd

groups=["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [56, 8, 19, 14, 6, 71]
#建立 Data Frame
ironmen_df = pd.DataFrame(ironmen, columns = ["ironmen"], index = groups)
ironmen_df.sort_index()

ironmen
Big Data         14
Cloud            19
DevOps            8
Modern Web       56
Security          6
自我挑戰組            71

# 雲端載入

In [2]:
import pandas as pd

url="https://storage.googleapis.com/2017_ithome_ironman/data/iris.csv"

iris_df = pd.read_csv(url)
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
iris_df.mean() # 取得平均數

Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [4]:
iris_df['Sepal.Length'].median() # 取得中位數

5.8

In [6]:
import pandas as pd

iris_df = pd.read_csv('iris.csv')
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
import pandas as pd

url="https://storage.googleapis.com/2017_ithome_ironman/data/iris.xlsx"

iris_df = pd.read_excel(url)
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# 自訂函數

In [9]:
import math

def circle(radius):
    area = radius * radius * math.pi
    return area

print(circle(10)) # 呼叫定義完的函式，並傳入10計算圓面積

314.1592653589793


In [11]:
import math

def circleArea(radius):
    area = radius * radius * math.pi
    return area
radius = input("請輸入圓的半徑:")
print("圓的半徑為", circle(float(radius)))

請輸入圓的半徑:50
圓的半徑為 7853.981633974483


# 交換排序法 example exchange sort

In [12]:
import random # 由小排到大

def exchange_sort(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range(i+1, len(input_list)):
            if a[i] > a[j]:
                a[i], a[j]=a[j], a[i]
    return a

my_vector = random.sample(range(0, 100), 10)
print(my_vector)
print(exchange_sort(my_vector))

[56, 40, 89, 76, 33, 71, 19, 52, 54, 10]
[10, 19, 33, 40, 52, 54, 56, 71, 76, 89]


In [13]:
import random 

def exchange_sort(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range(i+1, len(input_list)):
            if a[i] < a[j]:
                a[i], a[j]=a[j], a[i]
    return a

my_vector = random.sample(range(0, 100), 10)
print(my_vector)
print(exchange_sort(my_vector))

[13, 30, 63, 34, 78, 33, 56, 64, 26, 54]
[78, 64, 63, 56, 54, 34, 33, 30, 26, 13]
